export default {
  MACHINE_NO: 'machine no',
  PLACED_AT: 'placed at',
  NAME: 'name',
  PRICE: 'price',
  LOCATION: 'location',
  MACHINE_DETAILS: 'machine details',
  PHONE_NUMBER: 'phone number',
  BOOKED_STATUS: 'booked status',
  CHOOSE_DATE: 'choose date',
  PICK_AN_IMAGE: 'Pick Image',
  UPLOAD_AN_IMAGE: 'upload image',
  ADD_MACHINES: 'add machines',
  RENT: 'rent',
  ADD: 'add',
  ORDERS: 'orders',
  OPEN: 'open',
  ALL_ORDERS: 'All Orders',
  DESCRIPTION: 'Description',
  DATE: 'Date',
  ORDER_ID: 'Order ID',
  ORDERED_BY: 'Ordered by',
  EMAIL: 'Email',
  ADDRESS: 'Address',
  PAYMENT_STATUS: 'Payment Status',
  PAYMENT_MODE: 'Payment Mode',
  CREATE_YOUR_ACCOUNT: 'Create Your Account',
  USERNAME: 'UserName',
  PASSWORD: 'Password',
  SIGNUP: 'SignUp',
  LOGIN: 'Login',
  ALREADY_AN_ACCOUNT: 'Already have an Account',
  DONT_ACCOUNT: "Don't have an Account",
  EDIT_PROFILE: 'Edit Profile',
  CONTACT_US: 'Contact Us',
  EDIT_SAVE_PROFILE: 'Edit and save profile details and passwords ',
  HAVE_ANY_ISSUES: 'Have any issue? Contact us now',
  UPDATE: 'Update',
  LOGOUT: 'LogOut',
  UPLOAD_HERE: 'Upload Here',
  UPLOAD_FOUR_IMAGES: 'Upload 4 photos of machine to verify',
  DELIVERY_DATE: 'Delivery Date',
  ORDER: 'ORDER',
  OBH: 'OBH',
  BOOKED_TILL: 'Booked Till',
  TOTAL: 'Total',
  SHIP_TO: 'SHIP TO',
  CHOOSE_PAYEMENT_MODE: 'Choose Payement Method',
  ALL_MACHINES: 'All Machines',
  RENTED_MACHINES: 'Rented Machines',
  PROFILE: 'Profile',
  MY_ORDERS: 'My Orders',
  BOOK_NOW: 'Book Now',
  CHOOSE_DATE: 'Choose a Date',
  BACK: 'Back',
  BOOK: 'Book',
  CLICK_FRONT: 'Click the picture from Front',
  CLICK_RIGHT: 'Click the picture from Right',
  CLICK_BACK: 'Click the picture from Back',
  CLICK_LEFT: 'Click the picture from Left',
  SUBMIT: 'Submit',
  GET_TOUCH: 'Get in Touch with Us',
  LOVE_HEAR: 'We’d love to hear from you',
  NO_EASY_WAY: 'Here’s an easy way to reach us',
  SUBJECT: 'Subject*',
  NO_HELP: 'How can we help you ?*',
  WELCOME: ' Welcome farmers, renting farming machines is just a tap away!',
  CREATE_ONE: 'Create One',
  FILTER: 'Filter',
  SORT: 'Sort',
  FILTER_BY: 'Filter by choosing',
  CHOOSE_FILTER_OPTION: 'Choose Filter Option',
  SORT_NONE: 'Sort by: None',
  SORT_KVK: 'Sort by: KVK Name',
  SORT_MACHINE: 'Sort by: Machine Name',
  SORT_CREATED: 'Sort by: Created',
  FILTER_NONE: 'Filter by: None',
  FILTER_KVK: 'Filter by: KVK Name',
  FILTER_PRICE: 'Filter by: Price',
  CHOOSE_FILTER_VALUE: 'Choose Filter Value',
  PREVIOUS: 'Previous',
  NEXT: 'Next',
  CLOSE: 'Close',
  ON_RENT: 'On Rent',
  SEE_MORE: 'See More',
  GET_LOCATION: 'Get Location',
  CONTACT_NO: 'Contact Number',
  GETTING_STARTED: 'Getting Started',
  SEARCH: 'Search',
  MAP: 'Map',
  ENTER_FILTER_VALUE: 'Enter Filter Value',
};
