export default {
  MACHINE_NO: 'machine no',
  PLACED_AT: 'placed at',
  NAME: 'name',
  PRICE: 'price',
  LOCATION: 'location',
  MACHINE_DETAILS: 'machine details',
  PHONE_NUMBER: 'phone number',
  BOOKED_STATUS: 'booked status',
  CHOOSE_DATE: 'choose date',
  PICK_AN_IMAGE: 'pick image',
  UPLOAD_AN_IMAGE: 'upload image',
  ADD_MACHINES: 'add machines',
  RENT: 'rent',
  ADD: 'add',
  ORDERS: 'orders',
  OPEN: 'open',
  ALL_ORDERS: 'All Orders',
  DESCRIPTION: 'Description',
  DATE: 'Date',
  ORDER_ID: 'Order ID',
  ORDERED_BY: 'Ordered by',
  EMAIL: 'Email',
  ADDRESS: 'Address',
  PAYMENT_STATUS: 'Payment Status',
  PAYMENT_MODE: 'Payment Mode',
};
