export default {
  MACHINE_NO: 'machine no',
  PLACED_AT: 'placed at',
  NAME: 'name',
  PRICE: 'Price',
  LOCATION: 'location',
  MACHINE_DETAILS: 'machine details',
  PHONE_NUMBER: 'Phone Number',
  BOOKED_STATUS: 'booked status',
  CHOOSE_DATE: 'choose date',
  PICK_AN_IMAGE: 'Pick Image',
  UPLOAD_AN_IMAGE: 'Upload Images',
  ADD_MACHINES: 'add machines',
  RENT: 'rent',
  ADD: 'add',
  ORDERS: 'orders',
  OPEN: 'open',
  ALL_ORDERS: 'All Orders',
  DESCRIPTION: 'Description',
  DATE: 'Date',
  ORDER_ID: 'Order ID',
  EMAIL: 'Email *',
  ADDRESS: 'Address',
  PAYMENT_STATUS: 'Payment Status',
  PAYMENT_MODE: 'Payment Mode',
  CREATE_YOUR_ACCOUNT: 'Create Your Account',
  USERNAME: 'UserName *',
  PASSWORD: 'Password *',
  SIGNUP: 'SignUp',
  LOGIN: 'Login',
  ALREADY_AN_ACCOUNT: 'Already have an Account',
  DONT_ACCOUNT: "Don't have an Account",
  EDIT_PROFILE: 'Edit Profile',
  CONTACT_US: 'Contact Us',
  EDIT_SAVE_PROFILE: 'Edit and save profile details and passwords ',
  HAVE_ANY_ISSUES: 'Have any issue? Contact us now',
  UPDATE: 'Update',
  LOGOUT: 'LogOut',
  UPLOAD_HERE: 'Upload Here',
  UPLOAD_FOUR_IMAGES: 'Upload 4 photos of machine to verify',
  DELIVERY_DATE: 'Delivery Date',
  ORDER: 'ORDER',
  OBH: 'OBH',
  BOOKED_TILL: 'Booked Till',
  TOTAL: 'Total',
  SHIP_TO: 'SHIP TO',
  CHOOSE_PAYEMENT_MODE: 'Choose Payement Method',
  ALL_MACHINES: 'All Machines',
  RENTED_MACHINES: 'Rented Machines',
  PROFILE: 'Profile',
  MY_ORDERS: 'My Orders',
  BOOK_NOW: 'Book Now',
  CHOOSE_DATE: 'Choose a Date',
  BACK: 'Back',
  BOOK: 'Book',
  CLICK_FRONT: 'Click the picture from Front',
  CLICK_RIGHT: 'Click the picture from Right',
  CLICK_BACK: 'Click the picture from Back',
  CLICK_LEFT: 'Click the picture from Left',
  SUBMIT: 'Submit',
  GET_TOUCH: 'Get in Touch with Us',
  LOVE_HEAR: 'We’d love to hear from you',
  NO_EASY_WAY: 'Here’s an easy way to reach us',
  SUBJECT: 'Subject*',
  NO_HELP: 'How can we help you ?*',
  WELCOME:
    'Welcome farmers, renting farming machines and spray drones is just a tap away!',
  CREATE_ONE: 'Create One',
  FILTER: 'Filter',
  SORT: 'Sort',
  FILTER_BY: 'Filter by choosing',
  CHOOSE_FILTER_OPTION: 'Choose Filter Option',
  SORT_NONE: 'Sort by: None',
  SORT_KVK: 'Sort by: KVK Name',
  SORT_MACHINE: 'Sort by: Machine Name',
  SORT_CREATED: 'Sort by: Created',
  FILTER_NONE: 'Filter by: None',
  FILTER_KVK: 'Filter by: KVK Name',
  FILTER_PRICE: 'Filter by: Price',
  CHOOSE_FILTER_VALUE: 'Choose Filter Value',
  PREVIOUS: 'Previous',
  NEXT: 'Next',
  CLOSE: 'Close',
  ON_RENT: 'On Rent',
  SEE_MORE: 'See More',
  GET_LOCATION: 'Get Location',
  CONTACT_NO: 'Contact Number',
  GETTING_STARTED: 'Getting Started',
  SEARCH: 'Search',
  MAP: 'Map',
  ENTER_FILTER_VALUE: 'Enter Filter Value',
  VIEW_KVKS: 'View KVKs on Map',
  KVK_MAP: 'KVKs on Map',
  YOUR_MACHINES: 'Your Orders will be available here.',
  RENT_MACHINES: 'Your Rent Machines will be available here.',
  KVK_NAME: 'Name of KVK',
  KVK_ADDRESS: 'Address of KVK',
  KVK_HEAD: 'Head of KVK',
  CONTACT_KVK: 'Contact of KVK',
  ENTER_VALID: 'Enter valid 10 digit no.',
  KM_AWAY: 'km away from you',
  DAY: 'day',
  ORDER_PLACED: 'Order Placed',
  SUCCESS_UPLOAD: 'You have successfully uploaded the images.',
  DATE_RECEIVING: 'Date of Receiving',
  DELETE_ORDER: ' Delete Your Order',
  QUERY_RESOLVE: 'Query Resolved',
  QUERY_RESOLVEDD: 'Query will be resolved soon',
  MY_QUERIES: ' My Queries',
  SUBMITTED_QUERIESA: 'View Your Submitted Queries',
  CHOOSE_KVK: 'Choose KVK for the Query',
  BOOK_CALL: 'Book by a Call',
  YOUR_QUERY: 'Your Queries will be available here.',
  DRONE_RENT: 'Drone Rent',
  COMING_SOON: 'Coming Soon',
  DRONES: 'Drones',
  WHAT_TO_RENT: 'What you want to rent today?',
  TIME_SLOTS: 'Time Slots',
  Maintainer_INFO: 'Maintainer’s Information',
  CHEMICAL_ORDERED: 'Chemicals Ordered',
  COMPANY_INFO: 'Company’s Information',
  ADD_PESTICIDES: 'Add Pesticides',
  HOME_TEXT:
    'Welcome Farmers, Bhoomicam brings you a one stop platform for all your needs',
  MACHINE: 'Machines',
  DRONE: 'Drone',
  CHOOSE_ORDER_ID: 'Choose order Id',
  YOUR_ORDERS: 'Your Orders',
  DELIVERY_ADDRESS: 'Delivery Address',
  NEAR_LAND: 'Nearby Landmark',
  OWNER: 'Owner',
  CHEMICAL: 'Chemical',
  CHEMICAL_PRICE: 'Price of Chemical/Litre',
  FARM_AREA: 'Farm Area',
  DRONE_COMPANY: 'Drone Company Address',
  DRONE_COMPANY_CONTACT: 'Drone Company Contact',
  ORDER_DETS: 'Order Details',
  PROVIDING_PESTICIDES: 'Providing Pesticides',
  MAINTAINERS_ASSIGNED: 'No Operator Assigned till now.',
  ORDER_DELETE: 'Are you sure you want to delete your Order?',
  QUERY_DELETE: 'Are you sure you want to delete this Query?',
  SELECT_LANG: 'Select Language of the App',
  LOGOUT: 'Logout',
  DRONE_HOME: 'Bhoomicam Drone Based Spray Service',
  DRONE_HOM_DES:
    'Get the pesticide and other chemical spray service from Drones at your farms easily and cheaply',
  ALL_DRONES: 'All Drones',
  HOME: 'Home',
  GO_TO_MACHINE: 'Go To Machine',
  BOOK_DRONE: 'Book Drone',
  BOOK_ORDER: 'Book Order',
  TIME_SLOT: 'Time Slots',
  CHOOSE_FROM_PROFILE: 'or Choose From Profile',
  ADD_PESTICIDES: 'Add Pesticides',
  PESTICIDE_NOT: 'Pesticides Not offered',
  SELECTED_PESTI: 'Selected Pesticides:',
  AMOUNT: 'Amount',
  LITRE: 'litre',
  DELETE: 'Delete',
  ORDER_SUMMARY: 'Order Summary',
  ORIGINAL_PRICE: 'Original Price',
  DISCOUNT: 'Discount',
  APPLY: 'Apply',
  FINAL_PRICE: 'Final Price',
  CANCEL: 'Cancel',
  ENTER_ADDRESS: 'Enter Address for Order to be delivered',
  LAND: 'Enter Nearby Landmark',
  ACRE: 'Acre',
  BIGHA: 'Bigha',
  CASH_DELI: 'Cash on Delivery',
  ONLINEPAY: 'Online Payement',
  FARM_AREA: 'Farm Area',
  ENTER_COUPON: 'Enter Coupon Code',
  VALID_CREDS: 'Enter Valid Credentials',
  PLEASE_TRY_AGAIN: 'Error Try Again',
  PASSWORD_TOO_SHORT: 'Password too short',
  INVALID_EMAIL: 'Invalid Email',
  ORDER_SUCCESSFUL: 'Order Done Successfully',
  PLEASE_ENTER_CREDENTIALS: 'Please enter your credentials',
  INVALID_CREDENTIALS: 'The email or password is incorrect',
  CALL_PHONE_PERMISSION_ERROR:
    'You need to grant CALL_PHONE permission to make phone calls.',
  OPEN_PHONE_APP_ERROR: 'Failed to open the phone app or make the call.',
  CHECK_PHONE_APP_SUPPORT_ERROR:
    'An error occurred while checking phone app support:',
  QUERY_SUBMIT_ERROR: 'Error Submitting Query Check Fields',
  GRANT_CALL_PHONE_PERMISSION:
    'You need to grant CALL_PHONE permission to make phone calls.',
  FAILED_TO_MAKE_CALL: 'Failed to open phone app or make the call.',
  ERROR_CHECKING_PHONE_APP:
    'An error occurred while checking phone app support:',
  MESSAGE_DELIVERED: 'Message Delivered',
  UPDATE_PROFILE_BEFORE_ORDER: 'Update address in profile before you order',
  ERRIMG: 'Error in uploading images',
  ENTER_QUANTITY: 'Enter Quantity',
  SIGN_OTP: 'Signup with OTP',
  SIGN_EMAIL: 'Signup with Email',
  ENTER_OTP: 'Enter OTP',
  LOGIN_SIGNUP: 'Login or Sign Up',
  RECIEVE_OTP: 'Recieve OTP',
  INVALID_PHONE_NUMBER: 'Please Input a valid Phone Number',
  LOGIN_SIGNUP_DESCRIPTION: 'Login or sign up using mobile and OTP',
  AADHAR: 'Aadhar',
  OK: 'Ok',
  YOUR_QUERYS: 'Your Queries',
  DELETE_ORDER_ALERT: 'Are you sure you want to delete your Order?',
  ORDER_PESTICIDES: 'Do you want to order Pesticides',
  CROP_NAME: 'Enter Current Crop of your Field',
  CHOOSE_PESTICIDE: 'Choose Pesticide',
  PLEASE_ALERT: 'Please enter full details',
  ONE_PESTICIDE: 'You can only add 1 pesticide for a Order',
  INVALID_CODE: 'Invalid Code',
  UPDATE_SUCCESS: 'Updated Successfully',
  GO_TO_DRONE: 'Go to Drone',
  DELIVERY_ALERT:
    'You cannot delete your Order on Day of Delivery Contact Operator',
  LOGOUT_ALERT: 'Are you sure you want to logout?',
  CLOSE_ALERT: 'Do you want to close the application?',
  DRONE_COM: 'Drone Company',
  NO_RESULTS: 'No Results Found',
  SCHOOL: 'School',
  PANCHAYAT: 'Panchyat',
  VALIDATE_OTP: 'Validate OTP',
  RESEND_OTP: 'Resend OTP',
  DATE_RECEIVED: 'Date Received',
  SPRAY_COMPLETED: 'Spray Completed',
  REVIEW: 'Review',
  NO_PESTICIDES: 'No Pesticides Ordered',
  BHOOMICAM: 'Bhoomicam',
  DRONE_RENTAL: 'Drone Rental',
  RENTED_DRONES: 'Your Rented Drones will be available here',
};
