export default {
  MACHINE_NO: 'मशीन नं',
  PLACED_AT: 'कब रखा गया',
  NAME: 'नाम',
  PRICE: 'कीमत',
  LOCATION: 'जगह',
  MACHINE_DETAILS: 'मशीन विवरण',
  PHONE_NUMBER: 'फ़ोन नंबर',
  BOOKED_STATUS: 'बुक की गई स्थिति',
  CHOOSE_DATE: 'तिथि चुनें',
  PICK_AN_IMAGE: 'छवि चुनें',
  UPLOAD_AN_IMAGE: 'तस्विर अपलोड करना',
  ADD_MACHINES: 'किराए पर लें',
  RENT: 'किराया',
  ADD: 'जोड़ना',
  ORDERS: 'अनुरोध',
  OPEN: 'खोलिए',
  ALL_ORDERS: 'सभी आदेश',
  DESCRIPTION: 'विवरण',
  DATE: 'तारीख',
  ORDER_ID: 'क्रम संख्या',
  ORDERED_BY: '',
  EMAIL: 'ईमेल',
  ADDRESS: 'के द्वारा आदेश',
  PAYMENT_STATUS: 'भुगतान की स्थिति',
  PAYMENT_MODE: 'भुगतान का प्रकार',
};
