export default {
  MACHINE_NO: 'मशीन नं',
  PLACED_AT: 'कब रखा गया',
  NAME: 'नाम',
  PRICE: 'कीमत',
  LOCATION: 'जगह',
  MACHINE_DETAILS: 'मशीन विवरण',
  PHONE_NUMBER: 'फ़ोन नंबर',
  BOOKED_STATUS: 'बुक की गई स्थिति',
  CHOOSE_DATE: 'तिथि चुनें',
  PICK_AN_IMAGE: 'छवि चुनें',
  UPLOAD_AN_IMAGE: 'तस्विर अपलोड करें',
  ADD_MACHINES: 'किराए पर लें',
  RENT: 'किराया',
  ADD: 'जोड़े',
  ORDERS: 'ऑर्डर्स',
  OPEN: 'खोलिए',
  ALL_ORDERS: 'सभी ऑर्डर',
  DESCRIPTION: 'विवरण',
  DATE: 'तारीख',
  ORDER_ID: 'आर्डर संख्या',
  EMAIL: 'ईमेल *',
  ADDRESS: 'पता',
  PAYMENT_STATUS: 'भुगतान की स्थिति',
  PAYMENT_MODE: 'भुगतान का प्रकार',
  CREATE_YOUR_ACCOUNT: 'अपना खाता बनाएं',
  USERNAME: 'उपयोगकर्ता नाम *',
  PASSWORD: 'पासवर्ड *',
  SIGNUP: 'साइन अप करें',
  LOGIN: 'लॉग इन करें',
  ALREADY_AN_ACCOUNT: 'पहले से ही एक खाता है',
  DONT_ACCOUNT: 'खाता नहीं है',
  EDIT_PROFILE: 'प्रोफ़ाइल संपादित करें',
  CONTACT_US: 'संपर्क करें',
  EDIT_SAVE_PROFILE: 'प्रोफ़ाइल विवरण और पासवर्ड संपादित करें और सहेजें',
  HAVE_ANY_ISSUES: 'कोई समस्या है? हमसे अभी संपर्क करें',
  UPDATE: 'अपडेट',
  LOGOUT: 'लॉग आउट',
  DELIVERY_DATE: 'डिलीवरी की तारीख',
  ORDER: 'ऑर्डर',
  OBH: 'ओबीएच',
  BOOKED_TILL: 'तक बुक किया गया',
  TOTAL: 'कुल',
  SHIP_TO: 'यहां भेजें',
  UPLOAD_HERE: 'यहाँ अपलोड करें',
  UPLOAD_FOUR_IMAGES: 'सत्यापित करने के लिए मशीन की 4 फ़ोटो अपलोड करें',
  CHOOSE_PAYEMENT_MODE: 'भुगतान का तरीका चुनें',
  ALL_MACHINES: 'सभी मशीनें',
  RENTED_MACHINES: 'किराए की मशीनें',
  PROFILE: 'प्रोफ़ाइल',
  MY_ORDERS: 'मेरे ऑर्डर',
  BOOK_NOW: 'अभी बुक करें',
  CHOOSE_DATE: 'एक तिथि चुनें',
  BACK: 'पीछे',
  BOOK: 'बुक',
  CLICK_FRONT: 'तस्वीर को सामने से क्लिक करें',
  CLICK_RIGHT: 'तस्वीर को राइट से क्लिक करें',
  CLICK_BACK: 'तस्वीर को पीछे से क्लिक करें',
  CLICK_LEFT: 'तस्वीर को बाईं ओर से क्लिक करें',
  SUBMIT: 'सबमिट करें',
  GET_TOUCH: 'हमारे साथ जुड़े',
  LOVE_HEAR: 'हमें आपसे सुनकर अत्यंत खुशी होगी',
  NO_EASY_WAY: 'यहां हम तक पहुंचने का एक आसान तरीका है: ',
  SUBJECT: 'समस्या का विषय',
  NO_HELP: 'हम आपकी कैसे मदद कर सकते हैं ?',
  WELCOME:
    'किसानों का स्वागत है, कृषि मशीनें और स्प्रे ड्रोन किराए पर लेना बस एक टैप दूर है!',
  CREATE_ONE: 'एक बनाएँ',
  FILTER: 'फ़िल्टर',
  SORT: 'क्रम से लगाना',
  FILTER_BY: 'चुनकर फ़िल्टर करें',
  CHOOSE_FILTER_OPTION: 'फ़िल्टर विकल्प चुनें',
  SORT_NONE: 'क्रमबद्ध करें: कोई नहीं',
  SORT_KVK: 'क्रमबद्ध करें: केवीके नाम',
  SORT_MACHINE: 'क्रमबद्ध करें: मशीन का नाम',
  SORT_CREATED: 'क्रमबद्ध करें: बनाया गया',
  FILTER_NONE: 'फ़िल्टर करें: कोई नहीं',
  FILTER_KVK: 'फ़िल्टर करें: केवीके नाम',
  FILTER_PRICE: 'इसके अनुसार फ़िल्टर करें: कीमत',
  CHOOSE_FILTER_VALUE: 'फ़िल्टर मान चुनें',
  PREVIOUS: 'पिछला',
  NEXT: 'अगला',
  CLOSE: 'बंद करें',
  ON_RENT: 'किराए पर',
  SEE_MORE: 'और देखें',
  GET_LOCATION: 'स्थान प्राप्त करें',
  CONTACT_NO: 'संपर्क संख्या',
  GETTING_STARTED: 'शुरू करें',
  SEARCH: 'खोज करें',
  MAP: 'नक्शा',
  ENTER_FILTER_VALUE: 'फ़िल्टर मान दर्ज करें',
  VIEW_KVKS: 'मानचित्र पर केवीके देखें',
  KVK_MAP: 'मानचित्र पर केवीके',
  YOUR_MACHINES: 'आपके ऑर्डर यहां उपलब्ध होंगे.',
  RENT_MACHINES: 'आपकी किराये की मशीनें यहां उपलब्ध होंगी।',
  KVK_NAME: 'केवीके का नाम',
  KVK_ADDRESS: 'केवीके का पता',
  KVK_HEAD: 'केवीके के प्रमुख',
  CONTACT_KVK: 'केवीके से संपर्क करें',
  ENTER_VALID: 'मान्य 10 अंकों की संख्या दर्ज करें',
  KM_AWAY: 'आपसे किमी दूर',
  DAY: 'दिन',
  ORDER_PLACED: 'ऑर्डर किया गया',
  SUCCESS_UPLOAD: 'आपने सफलतापूर्वक चित्र अपलोड कर दिए हैं.',
  DATE_RECEIVING: 'प्राप्त करने की तिथि',
  DELETE_ORDER: 'अपना ऑर्डर हटाएं',
  QUERY_RESOLVE: 'समस्या का समाधान हो गया',
  QUERY_RESOLVEDD: 'जल्द ही समस्या का समाधान कर दिया जाएगा',
  MY_QUERIES: 'आपकी समस्याएं',
  SUBMITTED_QUERIESA: 'अपनी सबमिट की गई समस्याएं देखें',
  CHOOSE_KVK: 'समस्या के लिए केवीके चुनें',
  BOOK_CALL: 'कॉल द्वारा बुक करें',
  YOUR_QUERY: 'आपके प्रश्न यहां उपलब्ध होंगे.',
  DRONE_RENT: 'ड्रोन किराया',
  COMING_SOON: 'जल्द आ रहा है',
  DRONES: 'ड्रोन',
  WHAT_TO_RENT: 'आज आप क्या किराये पर लेना चाहते हैं?',
  TIME_SLOTS: 'समय स्लॉट्स',
  Maintainer_INFO: 'ऑपरेटर की जानकारी',
  CHEMICAL_ORDERED: 'रसायन का ऑर्डर दिया गया',
  COMPANY_INFO: 'कंपनी की जानकारी',
  HOME_TEXT:
    'किसानों का स्वागत है, भूमिकैम आपके लिए एक वन-स्टॉप प्लेटफॉर्म लेकर आया है',
  MACHINE: 'कृषियंत्र',
  DRONE: 'ड्रोन',
  CHOOSE_ORDER_ID: 'ऑर्डर आईडी चुनें',
  YOUR_ORDERS: 'आपके ऑर्डर',
  DELIVERY_ADDRESS: 'डिलिवरी का पता',
  NEAR_LAND: 'भूमि के निकट',
  OWNER: 'मालिक',
  CHEMICAL: 'केमिकल नाम',
  FARM_AREA: 'खेत क्षेत्र',
  ORDER_DETS: 'ऑर्डर का विवरण',
  DRONE_COMPANY: 'ड्रोन कंपनी एड्रेस  ',
  DRONE_COMPANY_CONTACT: 'ड्रोन कंपनी कांटेक्ट',
  PROVIDING_PESTICIDES: 'कीटनाशक उपलब्ध कराना',
  ADD_PESTICIDES: 'कीटनाशक जोड़ें',
  CHEMICAL_PRICE: 'केमिकल का मूल्य/लीटर',
  MAINTAINERS_ASSIGNED: 'अभी तक कोई ऑपरेटर नियुक्त नहीं किया गया है',
  ORDER_DELETE: 'क्या आप वाकई अपना ऑर्डर हटाना चाहते हैं?',
  QUERY_DELETE: 'क्या आप वाकई इस क्वेरी को हटाना चाहते हैं?',
  SELECT_LANG: 'भाषा चुने',
  DRONE_HOME: 'भूमिकैम ड्रोन आधारित स्प्रे सेवा',
  DRONE_HOM_DES:
    'अपने खेतों में ड्रोन से कीटनाशक और अन्य रासायनिक स्प्रे सेवा आसानी से और सस्ते में प्राप्त करें',
  ALL_DRONES: 'सभी ड्रोन',
  HOME: 'होम',
  GO_TO_MACHINE: 'कृषियंत्र पर जाएँ',
  BOOK_DRONE: 'बुक ड्रोन',
  BOOK_ORDER: 'बुक आर्डर',
  TIME_SLOT: 'समय स्लॉट्स',
  CHOOSE_FROM_PROFILE: 'या प्रोफ़ाइल से चुनें',
  ADD_PESTICIDES: 'कीटनाशक जोड़ें',
  PESTICIDE_NOT: 'कीटनाशक उपलब्ध नहीं है',
  SELECTED_PESTI: 'चयनित कीटनाशक:',
  AMOUNT: 'रकम',
  LITRE: 'लीटर',
  DELETE: 'हटाएं',
  ORDER_SUMMARY: 'आर्डर सारांश',
  ORIGINAL_PRICE: 'मूल मूल्य',
  DISCOUNT: 'छूट',
  APPLY: 'लागू करें',
  FINAL_PRICE: 'अंतिम मूल्य',
  CANCEL: 'रद्द करें',
  ENTER_ADDRESS: 'ऑर्डर को डिलीवर करने के लिए पता दर्ज करें',
  LAND: 'नजदीकी सीमा चिह्नित करें',
  ACRE: 'एकड़',
  BIGHA: 'बीघा',
  CASH_DELI: 'कैश ऑन डिलीवरी',
  ONLINEPAY: 'ऑनलाइन भुगतान',
  FARM_AREA: 'खेत क्षेत्र',
  ENTER_COUPON: 'कूपन कोड दर्ज करें',
  VALID_CREDS: 'मान्य क्रेडेंशियल दर्ज करें',
  PLEASE_TRY_AGAIN: 'कृपया पुन: प्रयास करें',
  PLEASE_TRY_AGAIN: 'पुनः प्रयास करें',
  PASSWORD_TOO_SHORT: 'पासवर्ड बहुत छोटा है',
  INVALID_EMAIL: 'अवैध ईमेल',
  ORDER_SUCCESSFUL: 'आदेश सफलतापूर्वक पूरा हुआ',
  PLEASE_ENTER_CREDENTIALS: 'कृपया अपनी प्रमाणिकता दर्ज करें',
  INVALID_CREDENTIALS: 'ईमेल या पासवर्ड गलत है',
  CALL_PHONE_PERMISSION_ERROR:
    'फोन कॉल न करने के लिए CALL_PHONE अनुमति देने की आवश्यकता है।',
  OPEN_PHONE_APP_ERROR: 'फोन ऐप खोलने या कॉल करने में विफल हुआ।',
  CHECK_PHONE_APP_SUPPORT_ERROR: 'फोन ऐप समर्थन की जांच करते समय त्रुटि हुई:',
  QUERY_SUBMIT_ERROR: 'प्रश्न सबमिट करते समय त्रुटि',
  GRANT_CALL_PHONE_PERMISSION:
    'कॉल करने के लिए CALL_PHONE अनुमति देने की आवश्यकता है।',
  FAILED_TO_MAKE_CALL: 'फोन ऐप खोलने या कॉल करने में विफल हुआ।',
  ERROR_CHECKING_PHONE_APP: 'फोन ऐप समर्थन की जांच करते समय त्रुटि हुई:',
  MESSAGE_DELIVERED: 'संदेश पहुंचाया गया',
  UPDATE_PROFILE_BEFORE_ORDER:
    'आपके ऑर्डर प्लेस करने से पहले अपना पता अपडेट करें',
  ERRIMG: 'छवि अपलोड करने में त्रुटि',
  ENTER_QUANTITY: 'मात्रा दर्ज करें',
  SIGN_OTP: 'ओटीपी के साथ साइनअप',
  SIGN_EMAIL: 'ईमेल से साइनअप करें',
  ENTER_OTP: 'ओटीपी दर्ज करें',
  LOGIN_SIGNUP: 'लॉगिन या साइन अप करें',
  RECIEVE_OTP: 'ओटीपी प्राप्त करें',
  INVALID_PHONE_NUMBER: 'कृपया एक वैध फ़ोन नंबर दर्ज करें',
  LOGIN_SIGNUP_DESCRIPTION:
    'मोबाइल और OTP का उपयोग करके लॉगिन करें या साइन अप करें',
  AADHAR: 'आधार',
  OK: 'ठीक है',
  YOUR_QUERYS: 'आपके प्रश्न',
  DELETE_ORDER_ALERT: 'क्या आप अपना आर्डर मिटाना चाहते हैं?',
  ORDER_PESTICIDES: 'क्या आप कीटनाशक मंगवाना चाहते हैं?',
  CROP_NAME: 'अपने खेत की वर्तमान फसल दर्ज करें',
  CHOOSE_PESTICIDE: 'कीटनाशक चुनें',
  PLEASE_ALERT: 'कृपया पूरा विवरण दर्ज करें',
  ONE_PESTICIDE: 'आप केवल एक कीटनाशक जोड़ सकते हैं',
  INVALID_CODE: 'अमान्य कोड',
  GO_TO_DRONE: 'ड्रोन पर जाएं',
  DELIVERY_ALERT: 'आप डिलीवरी के दिन अपना आर्डर नहीं हटा सकते हैं',
  LOGOUT_ALERT: 'क्या आप वाकई लॉगआउट करना चाहते हैं?',
  CLOSE_ALERT: 'क्या आप ऐप्लिकेशन को बंद करना चाहते हैं?',
  DRONE_COM: 'ड्रोन कंपनी',
  UPDATE_SUCCESS: 'सफलतापूर्वक अपडेट किया गया',
  NO_RESULTS: 'कोई परिणाम नहीं मिला',
  SCHOOL: 'विद्यालय',
  PANCHAYAT: 'पंचायत',
  VALIDATE_OTP: 'ओटीपी सत्यापित करें',
  RESEND_OTP: 'ओटीपी पुनः भेजें',
  DATE_RECEIVED: 'प्राप्ति दिनांक',
  SPRAY_COMPLETED: 'स्प्रे पूरा हुआ',
  REVIEW: 'रिव्यु',
  NO_PESTICIDES: 'किसी कीटनाशक का ऑर्डर नहीं दिया गया',
  BHOOMICAM: 'भूमिकैम',
  DRONE_RENTAL: 'ड्रोन रेंटल',
  RENTED_DRONES: 'आपके किराए पर लेए गए ड्रोन यहाँ उपलब्ध होंगे',
};
