export default {
  MACHINE_NO: 'मशीन नं',
  PLACED_AT: 'कब रखा गया',
  NAME: 'नाम',
  PRICE: 'कीमत',
  LOCATION: 'जगह',
  MACHINE_DETAILS: 'मशीन विवरण',
  PHONE_NUMBER: 'फ़ोन नंबर',
  BOOKED_STATUS: 'बुक की गई स्थिति',
  CHOOSE_DATE: 'तिथि चुनें',
  PICK_AN_IMAGE: 'छवि चुनें',
  UPLOAD_AN_IMAGE: 'तस्विर अपलोड करना',
  ADD_MACHINES: 'किराए पर लें',
  RENT: 'किराया',
  ADD: 'जोड़ना',
  ORDERS: 'अनुरोध',
  OPEN: 'खोलिए',
  ALL_ORDERS: 'सभी आदेश',
  DESCRIPTION: 'विवरण',
  DATE: 'तारीख',
  ORDER_ID: 'क्रम संख्या',
  ORDERED_BY: '',
  EMAIL: 'ईमेल',
  ADDRESS: 'के द्वारा आदेश',
  PAYMENT_STATUS: 'भुगतान की स्थिति',
  PAYMENT_MODE: 'भुगतान का प्रकार',
  CREATE_YOUR_ACCOUNT: 'अपना खाता बनाएं',
  USERNAME: 'उपयोगकर्ता नाम',
  PASSWORD: 'पासवर्ड',
  SIGNUP: 'साइन अप करें',
  LOGIN: 'लॉग इन करें',
  ALREADY_AN_ACCOUNT: 'पहले से ही एक खाता है',
  DONT_ACCOUNT: 'खाता नहीं है',
  EDIT_PROFILE: 'प्रोफ़ाइल संपादित करें',
  CONTACT_US: 'संपर्क करें',
  EDIT_SAVE_PROFILE: 'प्रोफ़ाइल विवरण और पासवर्ड संपादित करें और सहेजें',
  HAVE_ANY_ISSUES: 'कोई समस्या है? हमसे अभी संपर्क करें',
  UPDATE: 'अद्यतन',
  LOGOUT: 'लॉग आउट',
  DELIVERY_DATE: 'डिलीवरी की तारीख',
  ORDER: 'ऑर्डर',
  OBH: 'ओबीएच',
  BOOKED_TILL: 'तक बुक किया गया',
  TOTAL: 'कुल',
  SHIP_TO: 'यहां भेजें',
  UPLOAD_HERE: 'यहाँ अपलोड करें',
  UPLOAD_FOUR_IMAGES: 'सत्यापित करने के लिए मशीन की 4 फ़ोटो अपलोड करें',
  CHOOSE_PAYEMENT_MODE: 'भुगतान का तरीका चुनें',
  ALL_MACHINES: 'सभी मशीनें',
  RENTED_MACHINES: 'किराए की मशीनें',
  PROFILE: 'प्रोफ़ाइल',
  MY_ORDERS: 'मेरे ऑर्डर',
  BOOK_NOW: 'अभी बुक करें',
  CHOOSE_DATE: 'एक तिथि चुनें',
  BACK: 'पीछे',
  BOOK: 'बुक',
  CLICK_FRONT: 'तस्वीर को सामने से क्लिक करें',
  CLICK_RIGHT: 'तस्वीर को राइट से क्लिक करें',
  CLICK_BACK: 'तस्वीर को पीछे से क्लिक करें',
  CLICK_LEFT: 'तस्वीर को बाईं ओर से क्लिक करें',
  SUBMIT: 'सबमिट करें',
  GET_TOUCH: 'हमारे साथ जुड़े',
  LOVE_HEAR: 'हमें आपसे सुनकर अत्यंत खुशी होगी',
  NO_EASY_WAY: 'यहां हम तक पहुंचने का एक आसान तरीका है: ',
  SUBJECT: 'समस्या का विषय',
  NO_HELP: 'हम आपकी कैसे मदद कर सकते हैं ?',
  WELCOME:
    'स्वागत किसानों को, किराये पर कृषि मशीनों की सुविधा एक टैप की दूरी पर है!',
  CREATE_ONE: 'एक बनाएँ',
  FILTER: 'फ़िल्टर',
  SORT: 'क्रम से लगाना',
  FILTER_BY: 'चुनकर फ़िल्टर करें',
  CHOOSE_FILTER_OPTION: 'फ़िल्टर विकल्प चुनें',
  SORT_NONE: 'क्रमबद्ध करें: कोई नहीं',
  SORT_KVK: 'क्रमबद्ध करें: केवीके नाम',
  SORT_MACHINE: 'क्रमबद्ध करें: मशीन का नाम',
  SORT_CREATED: 'क्रमबद्ध करें: बनाया गया',
  FILTER_NONE: 'फ़िल्टर करें: कोई नहीं',
  FILTER_KVK: 'फ़िल्टर करें: केवीके नाम',
  FILTER_PRICE: 'इसके अनुसार फ़िल्टर करें: कीमत',
  CHOOSE_FILTER_VALUE: 'फ़िल्टर मान चुनें',
  PREVIOUS: 'पिछला',
  NEXT: 'अगला',
  CLOSE: 'बंद करें',
  ON_RENT: 'किराए पर',
  SEE_MORE: 'और देखें',
  GET_LOCATION: 'स्थान प्राप्त करें',
  CONTACT_NO: 'संपर्क संख्या',
  GETTING_STARTED: 'शुरू करें',
  SEARCH: 'खोज करें',
  MAP: 'नक्शा',
  ENTER_FILTER_VALUE: 'फ़िल्टर मान दर्ज करें',
  QUERY_NO: 'प्रश्न सं',
  USERNAME: 'उपयोगकर्ता नाम',
  MESSAGE: 'संदेश',
  MARK_RESOLVED: 'हल किया',
};
